### PR TITLE
feat(mergify): automatically merge bot dependency upgrades

### LINKED ISSUE #1418: Use mergify to automatically approve and merge automated PRs
Bots such as _dependabot_ and _snyk_ frequently open PRs to patch security vulnerabilities. These can be merged automatically by another bot, such as [mergify](https://github.com/marketplace/mergify).

TODOs
- Integrate _mergify_
- Avoid automatically merging PRs for major version changes

See the Forms repository for an example.

### PR DESCRIPTION
**Pull request by liangyuanruo**
This PR instructs the mergify bot to automatically merge pull requests from

1. dependabot
2. Snyk.io

Pull requests are automatically merged if

1. The proposed upgrade is a non-major version change (dependabot only)
2. All existing CI checks pass

Closes #1418

### CODE REVIEW

**Comment by LoneRifle** [comment]
I had a think about this - I want to try to dump all the dependabot-related commits into its own branch, so mergify should be directed to accommodate that too. Given that there is other work that goes on in `develop`, we should incorporate the Auto Update GitHub Action too. 

With that in place, we can squash and merge dependency updates just once per release cycle, prior to pre-release testing. This gives us the automation from mergify while also keeping commit log noise to a minimum.

wdyt?

**Comment by liangyuanruo** [comment]
@LoneRifle don't merge yet, testing rule validity

**Comment by liangyuanruo** [comment]
> @LoneRifle don't merge yet, testing rule validity

ok it should be good to go

**Comment by mantariksh** [comment]
as per Forms, we can actually rely on branch protections to ensure that PRs don't get merged unless all CI checks pass, rather than having to keep the mergify config in sync with the CI steps

**Comment by liangyuanruo** [comment]
> as per Forms, we can actually rely on branch protections to ensure that PRs don't get merged unless all CI checks pass, rather than having to keep the mergify config in sync with the CI steps

Although you're right that it won't affect this repository, it's possible that someone cloning the repository will not configure their branch protections properly. Usually explicit is better than implicit, and we should also avoid relying on side effects.

**Review by LoneRifle — APPROVED** [review]
eh, lgtm.

**Comment by mantariksh** [comment]
@liangyuanruo okay, but tbh sounds like a lot of work just to optimise for a hypothetical person cloning the repo

**Pull request merged**
