### PR TITLE
Fix/link tagging for file upload

### PR DESCRIPTION
**Pull request by jimvae**
## Problem

Link tagging for file upload

## Solution

Add logic to add tags when creating link from file

## Before & After Screenshots

**BEFORE**: Tags were not included in the HTTP request
image
image

**AFTER**: 
Screen Shot 2022-09-27 at 6 15 24 PM
Screen Shot 2022-09-27 at 6 16 18 PM
Screen Shot 2022-09-27 at 6 19 08 PM

### CODE REVIEW

**Comment by jimvae** [comment]
Also added a fix to reset the tag state every time we create a url / close the `create url modal`.

**Comment by halfwhole** [comment]
for resetting the tag state after link creation, i believe #1982 should take care of it! as for resetting on close modal lgtm, though iirc shortlinks/long urls are not reset either when the modal closes

**Comment by jimvae** [comment]
> for resetting the tag state after link creation, i believe #1982 should take care of it! as for resetting on close modal lgtm, though iirc shortlinks/long urls are not reset either when the modal closes

alright, reverted the commit that does this!

**Review by halfwhole — APPROVED** [review]
LGTM, thanks for the catch!

(note for future: we might want to refactor the actions sometime, the current layout looks a bit messy sadly)

**Pull request merged**
