### PR TITLE
docs(readme): lint markdown and add complementary information for Mac computers with Apple Silicon

### PR DESCRIPTION
**Pull request by TheodoreGC**

### CODE REVIEW

**Comment by gweiying** [comment]
Looks good, did you use some kind of linter to lint the markdown?

**Review by gweiying — APPROVED** [review]
lgtm

**Comment by TheodoreGC** [comment]
@gweiying

Yes, I used the `markdownlint` extension for VS Code. It's available [here](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint).

For a detailed definition for the rules, you can have a look [there](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md).

**Comment by halfwhole** [comment]
linting for markdown sounds great actually! would it be a good idea to add it to our pre-commit hooks?
also we favour using squash and merge as our merge strategy 🙏

**Comment by TheodoreGC** [comment]
@halfwhole, That's possible indeed. You may want to check [there](https://github.com/DavidAnson/markdownlint-cli2#pre-commit) for adding it to pre-commit hook.

Alternatively, you could check that [repo](https://github.com/github/super-linter) for GitHub actions with broader linting possibilities.

I didn't know you were squashing and merging for your strategy. I did it locally (squashing) before pushing the changes.

**Pull request merged**
