### PR TITLE
build(dockerfiles): split dockerfile into production and dev

### LINKED ISSUE #178: Shard Dockerfile into development and production variants
**Is your feature request related to a problem? Please describe.**
The existing Dockerfile caters to both development and production builds, which increases the container startup time for developers and overall complexity.

**Describe the solution you'd like**
Shard existing Dockerfile into two separate files for development and production.

### PR DESCRIPTION
**Pull request by orbitalsqwib**
## Problem

The existing Dockerfile caters to both development and production builds, which increases the container startup time for developers and overall complexity.

Closes #178

## Solution

- split Dockerfile into production and development dockerfiles
- removed unnecessary conditionals for production dockerfile
- updated docker-compose to use development dockerfile

### CODE REVIEW

**Review by liangyuanruo — CHANGES_REQUESTED** [review]
Thanks for tackling this! Have you tried deploying to the staging environment? I think the rename to Dockerfile.production might break the Travis pipeline / Elastic Beanstalk deployment.

**Comment by orbitalsqwib** [comment]
> Thanks for tackling this! Have you tried deploying to the staging environment? I think the rename to Dockerfile.production might break the Travis pipeline / Elastic Beanstalk deployment.

I'm working on the build pipeline for edu right now, so i'll take a look at that too. Thanks for the heads up!

**Review by LoneRifle — CHANGES_REQUESTED** [review]
rebase changes on top of develop. in addition, consider using `Dockerfile` and `Dockerfile.dev` for deployments and localhost builds respectively

**Review by LoneRifle — APPROVED** [review]
lgtm

**Pull request merged**
